#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

const OUT_DIR = path.resolve(__dirname, "../out");
const ABI_SRC = path.resolve(__dirname, "../../packages/abi/src");

const CONTRACTS = [
  "CapitalManager",
  "DecisionLog",
  "ReputationOracle",
  "VUSDC",
  "AaveV3UsdcAdapter",
  "AaveV3WethAdapter",
  "BybitAttestor",
  "MerchantMoeAdapter",
  "LendleAdapter",
  "MethProtocolAdapter",
  "EthenaAdapter",
];

function findArtifact(name) {
  const contractDir = path.join(OUT_DIR, `${name}.sol`);
  const artifactPath = path.join(contractDir, `${name}.json`);
  if (!fs.existsSync(artifactPath)) {
    throw new Error(`Artifact not found: ${artifactPath}\nRun 'forge build' first.`);
  }
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
  return artifact.abi;
}

fs.mkdirSync(ABI_SRC, { recursive: true });

const abis = {};
for (const name of CONTRACTS) {
  abis[name] = findArtifact(name);
}

// Write abis.json
fs.writeFileSync(path.join(ABI_SRC, "abis.json"), JSON.stringify(abis, null, 2));
console.log("Wrote abis.json");

// Write index.ts with typed exports
const lines = [
  `// Auto-generated by scripts/export-abi.js — do not edit manually`,
  `import abis from "./abis.json";`,
  `export { abis };`,
  `export * from "./addresses";`,
  ``,
];
for (const name of CONTRACTS) {
  lines.push(`export const ${name}ABI = ${JSON.stringify(abis[name], null, 2)} as const;`);
  lines.push(``);
}

fs.writeFileSync(path.join(ABI_SRC, "index.ts"), lines.join("\n"));
console.log("Wrote index.ts");

console.log(`\nExported ABIs for: ${CONTRACTS.join(", ")}`);
