# shellcheck shell=bash
# deploy.sh — local deploy of Deploy.s.sol Phase A onto the anvil fork,
# then parse the broadcast JSON and write .env.local.

[[ -n "${_VAULT_DEPLOY_LOADED:-}" ]] && return 0
_VAULT_DEPLOY_LOADED=1

source "$VAULT_ROOT/scripts/lib/common.sh"
source "$VAULT_ROOT/scripts/lib/anvil.sh"

deploy_local() {
  local rpc="http://127.0.0.1:$ANVIL_PORT"

  # One-shot atomic deploy of the full stack (CapitalManager + vUSDC +
  # DecisionLog + ReputationOracle + adapters). Uses DeployLocal.s.sol,
  # NOT the mainnet Deploy.s.sol (which is two-phase and transfers
  # ownership to a Safe — neither applies in local dev).
  export DEPLOYER_ADDRESS="$ANVIL_DEPLOYER_ADDR"
  export AGENT_ADDRESS="$ANVIL_AGENT_ADDR"
  export ATTESTOR_ADDRESS="$ANVIL_SAFE_ADDR"
  export AGENT_ID="${AGENT_ID:-1}"
  unset SEQUENCER_FEED REGISTRY_8004

  log_info "deploying full stack to anvil (DeployLocal.s.sol)"
  ( cd "$VAULT_ROOT/contracts" && \
    forge script script/DeployLocal.s.sol:DeployLocal \
      --rpc-url "$rpc" \
      --broadcast \
      --private-key "$ANVIL_DEPLOYER_PK" \
      --slow ) || die "forge script failed. Re-run with -vvv for details."

  parse_broadcast "$ANVIL_CHAIN_ID" DeployLocal.s.sol
}

# Reads contracts/broadcast/<script>/<chainId>/run-latest.json and emits
# addresses as 'KEY=0x...' lines on stdout (used by write_env_local).
extract_addresses() {
  local chain_id=$1
  local script_name="${2:-DeployLocal.s.sol}"
  local file="$VAULT_ROOT/contracts/broadcast/$script_name/$chain_id/run-latest.json"
  [[ -f $file ]] || die "broadcast file not found: $file"

  # For each contract type, pick the LAST CREATE tx in the broadcast.
  # (If something was re-deployed mid-script, the last one is authoritative.)
  pick() {
    jq -r --arg n "$1" '
      [.transactions[]
       | select(.transactionType == "CREATE" and .contractName == $n)]
      | last.contractAddress // empty
    ' "$file"
  }

  local cm vusdc dlog oracle ua wa ba moe mm le mp ea
  cm=$(pick CapitalManager)
  vusdc=$(pick VUSDC)
  dlog=$(pick DecisionLog)
  oracle=$(pick ReputationOracle)
  ua=$(pick AaveV3UsdcAdapter)
  wa=$(pick AaveV3WethAdapter)
  ba=$(pick BybitAttestor)
  moe=$(pick MerchantMoeRouter)
  mm=$(pick MerchantMoeAdapter)
  le=$(pick LendleAdapter)
  mp=$(pick MethProtocolAdapter)
  ea=$(pick EthenaAdapter)

  [[ -n $cm     ]] || die "CapitalManager not found in broadcast"
  [[ -n $vusdc  ]] || die "VUSDC not found in broadcast"
  [[ -n $dlog   ]] || die "DecisionLog not found in broadcast"
  [[ -n $oracle ]] || die "ReputationOracle not found in broadcast"
  [[ -n $ua     ]] || die "AaveV3UsdcAdapter not found in broadcast"
  [[ -n $wa     ]] || die "AaveV3WethAdapter not found in broadcast"
  [[ -n $ba     ]] || die "BybitAttestor not found in broadcast"

  cat <<EOF
CAPITAL_MANAGER_ADDRESS=$cm
VUSDC_ADDRESS=$vusdc
DECISION_LOG_ADDRESS=$dlog
REPUTATION_ORACLE_ADDRESS=$oracle
AAVE_V3_USDC_ADAPTER=$ua
AAVE_V3_WETH_ADAPTER=$wa
BYBIT_ATTESTOR_ADAPTER=$ba
MERCHANT_MOE_ROUTER=$moe
MERCHANT_MOE_ADAPTER=$mm
LENDLE_ADAPTER=$le
METH_ADAPTER=$mp
ETHENA_ADAPTER=$ea
EOF
}

parse_broadcast() {
  local chain_id=$1
  local script_name="${2:-DeployLocal.s.sol}"
  local kv
  kv=$(extract_addresses "$chain_id" "$script_name") || die "address extraction failed"

  # shellcheck disable=SC2034
  while IFS='=' read -r k v; do
    case "$k" in
      CAPITAL_MANAGER_ADDRESS)   CAPITAL_MANAGER_ADDRESS=$v ;;
      VUSDC_ADDRESS)             VUSDC_ADDRESS=$v ;;
      DECISION_LOG_ADDRESS)      DECISION_LOG_ADDRESS=$v ;;
      REPUTATION_ORACLE_ADDRESS) REPUTATION_ORACLE_ADDRESS=$v ;;
      AAVE_V3_USDC_ADAPTER)      AAVE_V3_USDC_ADAPTER=$v ;;
      AAVE_V3_WETH_ADAPTER)      AAVE_V3_WETH_ADAPTER=$v ;;
      BYBIT_ATTESTOR_ADAPTER)    BYBIT_ATTESTOR_ADAPTER=$v ;;
    esac
  done <<<"$kv"

  write_env_local
  log_info "addresses written to .env.local"
}

write_env_local() {
  local tmp
  tmp=$(mktemp "$VAULT_ROOT/.env.local.XXXXXX")
  local usdc="0x09Bc4E0D864854c6aFB6eB9A9cdF58aC190D0dF9"  # Mantle USDC (forked)
  cat >"$tmp" <<EOF
# auto-generated by ./vault.sh local start — DO NOT EDIT MANUALLY
# Regenerated on every \`vault.sh local start\` after Deploy.s.sol broadcast.
# User-managed secrets/RPC keys belong in .env, not here.

# Network (anvil fork of Mantle mainnet)
MANTLE_RPC_URL=http://127.0.0.1:$ANVIL_PORT
CHAIN_ID=$ANVIL_CHAIN_ID
NEXT_PUBLIC_RPC_URL=http://127.0.0.1:$ANVIL_PORT
NEXT_PUBLIC_CHAIN_ID=$ANVIL_CHAIN_ID

# DB
DATABASE_URL=$(local_database_url)

# Agent EOA — anvil dev account #1 (matches AGENT_ADDRESS used at deploy)
AGENT_PRIVATE_KEY=0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
AGENT_ADDRESS=$ANVIL_AGENT_ADDR

# Deployed contracts
CAPITAL_MANAGER_ADDRESS=$CAPITAL_MANAGER_ADDRESS
VUSDC_ADDRESS=$VUSDC_ADDRESS
DECISION_LOG_ADDRESS=$DECISION_LOG_ADDRESS
REPUTATION_ORACLE_ADDRESS=$REPUTATION_ORACLE_ADDRESS
AAVE_V3_USDC_ADAPTER=$AAVE_V3_USDC_ADAPTER
AAVE_V3_WETH_ADAPTER=$AAVE_V3_WETH_ADAPTER
BYBIT_ATTESTOR_ADAPTER=$BYBIT_ATTESTOR_ADAPTER

# Web (Next.js NEXT_PUBLIC_*)
NEXT_PUBLIC_CAPITAL_MANAGER_ADDRESS=$CAPITAL_MANAGER_ADDRESS
NEXT_PUBLIC_VUSDC_ADDRESS=$VUSDC_ADDRESS
NEXT_PUBLIC_DECISION_LOG_ADDRESS=$DECISION_LOG_ADDRESS
NEXT_PUBLIC_REPUTATION_ORACLE_ADDRESS=$REPUTATION_ORACLE_ADDRESS
NEXT_PUBLIC_AAVE_USDC_ADAPTER_ADDRESS=$AAVE_V3_USDC_ADAPTER
NEXT_PUBLIC_AAVE_WETH_ADAPTER_ADDRESS=$AAVE_V3_WETH_ADAPTER
NEXT_PUBLIC_BYBIT_ATTESTOR_ADDRESS=$BYBIT_ATTESTOR_ADAPTER
NEXT_PUBLIC_USDC_ADDRESS=$usdc
EOF
  mv "$tmp" "$VAULT_ROOT/.env.local"
}
