# shellcheck shell=bash
# env.sh — loaders for .env and .env.local.
#
# Two-layer model: .env is user-managed (secrets, RPC URLs, etc.),
# .env.local is auto-generated by ./vault.sh after a fresh deploy
# (contract addresses + DATABASE_URL). Order matters — .env.local
# overrides .env so a fresh deploy always wins.

[[ -n "${_VAULT_ENV_LOADED:-}" ]] && return 0
_VAULT_ENV_LOADED=1

source "$VAULT_ROOT/scripts/lib/common.sh"

load_env() {
  if [[ -f "$VAULT_ROOT/.env" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$VAULT_ROOT/.env"
    set +a
  else
    log_warn ".env not found at $VAULT_ROOT/.env — most commands will fail"
  fi
}

load_env_local() {
  if [[ -f "$VAULT_ROOT/.env.local" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$VAULT_ROOT/.env.local"
    set +a
  fi
}
